openapi: "3.0.0"
info:
  version: 0.0.1
  title: shortener Api
servers:
  - url: /
    description: Api

paths:

  /v1/urls/get-short-url:
    post:
      summary: Получить короткую ссылку
      operationId: urls_get_short_url
      tags:
        - /v1/urls
      requestBody:
        description: Тело запроса на получение короткой ссылки
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
            example:
              {
                "url": "https://github.com/porodoxs/url-shortener"
              }
      responses:
        '200':
          description: Короткая ссылка
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
              example:
                {
                  "short_url": "http://localhost:8080/HfO2g1"
                }
        '400':
          description: Ошибка в переданных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResponse'

components:

  schemas:
    InvalidResponse:
      type: object
      description: Формат ошибки
      required:
        - code
        - message
        - clarification
      properties:
        code:
          type: string
          description: Строковый код ошибки
        message:
          type: string
          description: Текст ошибки
        clarification:
          type: object
          description: Уточнение ошибки
